version: '2'
services:
  
  dashboard-api:
    build: .
    expose:
      - 80
    environment:
      VIRTUAL_HOST: dashboard.cloudpotato.nl
      LETSENCRYPT_HOST: dashboard.cloudpotato.nl
      LETSENCRYPT_EMAIL: marc0tjevp@gmail.com
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
